name: First Workflow

on: # 언제 워크플로우를 시작할지
  push:

jobs: # 어떤 작업들을 수행할지
  echo-log: # 작업 식별자
    runs-on: ubuntu-latest # 어떤 환경에서 작업이 돌아가는지 설정
    steps:
      - run: echo 'Hello World My first workflow' # 하나의 step 앞에 - 를 붙임
      - run: echo 'Same Same console.log and echo'

    # echo-log라는 job에서 2개의 step을 가진 워크플로우가 일어난다?! 라는 의미

  pwd-ls:
    name: PWD & LS
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: pwd
      - name: List files
        run: ls -al

  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ls -al
