name: First Workflow

on: # 언제 워크플로우를 시작할지
  push:

jobs: # 어떤 작업들을 수행할지
  echo-log: # 작업 식별자
    runs-on: ubuntu-latest # 어떤 환경에서 작업이 돌아가는지 설정
    steps:
      - run: echo 'Hello World My first workflow'
      - run: echo 'Same Same console.log and echo'
